server:
  port: 8788

spring:
  application:
    name: sttorage-provider
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://DESKTOP-70RB78L:3306/tencent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jk.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true